# Generated by Django 4.1.12 on 2023-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='music.category'),
        ),
    ]
