# Generated by Django 4.1.12 on 2023-12-02 13:52

import apps.base.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to=apps.base.services.get_path_update_category),
            preserve_default=False,
        ),
    ]
