# Generated by Django 4.1.12 on 2023-11-29 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music',
        ),
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.FileField(default=1, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
            preserve_default=False,
        ),
    ]
