# Generated by Django 4.1.12 on 2023-11-30 12:42

import apps.base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_music_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.FileField(upload_to=apps.base.services.get_path_update_cover, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(upload_to=apps.base.services.get_path_update_cover),
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums', to='music.album'),
        ),
    ]
