# Generated by Django 4.1.12 on 2023-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
