# Generated by Django 4.1.12 on 2023-12-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
