# Generated by Django 4.1.12 on 2023-11-30 12:42

import apps.base.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=apps.base.services.default_avatar, upload_to=apps.base.services.get_path_update_avatar),
        ),
    ]
