# Generated by Django 4.1.12 on 2023-12-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
